### ISSUE TITLE
Monitoring of the Administrator (Bultin)

### ISSUE THREAD

**Issue by VincentSTH** [lazywinadmin/Monitor-ADGroupMembership#26]
We have set up supervision for several groups successfully on the active Directory
But the monitoring of the Administrator (Bultin) group does not work.
The first time we run the script, it does not create the csv file and indicates that :"AVERTISSEMENT : [PROCESS] Something went wrong "

Can you help us ? 
Thank you

**Comment by lazywinadmin** [comment]
Just want to validate something, by "Administrator (Bultin)" Do you mean the local administrators group ?

**Comment by VincentSTH** [comment]
Indeed, it is the local administrator group of the server. When creating the Active directory server, this group is transformed into a local group integrated into the Active Directory.
See screenshot below
![capture](https://user-images.githubusercontent.com/35223623/34712413-10df8448-f523-11e7-88f9-eacef6edd2d6.JPG)
![capture2](https://user-images.githubusercontent.com/35223623/34712450-23491496-f523-11e7-9e8d-2d4cd42368a5.JPG)
