### ISSUE TITLE
Support for emailing via Office365

### ISSUE THREAD

**Issue by KingRob-GH** [lazywinadmin/Monitor-ADGroupMembership#43]
Is it possible to send the email via Office365 (ie smtp.office365.com)?

**Comment by JaimeStill** [comment]
I've created a revised version of the script that makes use of `Send-MailMessage` as opposed to using the `SmptClient` object for managing the mail transactions. As we found yesterday, it works with Office365. Leaving here in case @lazywinadmin might be interested: [Revised Monitor-ADGroupMembership](https://github.com/JaimeStill/Monitor-ADGroupMembership)

**Comment by lazywinadmin** [comment]
Thanks @JaimeStill 
Could you do a Pull request to update the code of the script ? (just to give you credit and show your name in contributors)
We could either support both approach or mark it as a breaking change in the changelog.
Let me know, else I can implement it sometimes this week.

**Comment by JaimeStill** [comment]
@lazywinadmin PR submitted

**Comment by lazywinadmin** [comment]
This was implemented in the last version
