### ISSUE TITLE
Change-History 6 times

### ISSUE THREAD

**Issue by marcohofbeck** [lazywinadmin/Monitor-ADGroupMembership#47]
Hi, 

hope anyone can help me. 
If something was changed on a AD group, the email would be send 6 times. Also in the change history we have the change 6 times.. 

Can anyone help me? I tried to troubleshoot, but without success. 

Thanks 
Marco

**Comment by lazywinadmin** [comment]
Hey @marcohofbeck 
Sounds like the script ran multiple times.
Is there any log you can share here ? Please replace identification/sensitive data

**Comment by marcohofbeck** [comment]
I solved the problem by myself. Thanks for the Response. 

In the Task the "run parallel"-Option was enabled. After disabling this option, everything works fine. 

Thanks and Regards, 
Marco

**Comment by lazywinadmin** [comment]
Great, thanks for the follow up @marcohofbeck 
I'll add this in the doc if someone run into the same pb.
